build-npm:
  stage: build
  image: node:8.11
  script:
  - npm install
  - npm run build
  artifacts:
    paths:
      - dist


pages:
  stage: deploy
  dependencies:
    - build-npm
  script:
  - ls -la 
  - mv public/ public_src/
  - ls -la 
  - mv dist/ public/
  - ls -la 
  - cd public 
  - ls -la 

  only:
  - master
  artifacts:
    paths:
      - public
