build:
  stage: build
  image: node:8.11
  script:
  - npm install
  - npm run build
  artifacts:
    paths:
      - dist


pages:
  stage: deploy
  dependencies:
    - build
  script:
  - mv dist/ public/
  only:
  - master
  artifacts:
    paths:
      - public
