build-npm:
  stage: build
  image: node:8.11
  script:
  - npm install
  - npm run build:gitlab:demo
  - npm run build:gitlab:prod
  artifacts:
    paths:
      - dist


pages:
  stage: deploy
  dependencies:
    - build-npm
  script:
  - mv public/ public_src/
  - mv dist_gitlab_prod/ public/
  - mv dist_gitlab_demo/ public/demo/
  # Serve a compressed version to speed up the loading
  # https://gitlab.com/gitlab-org/gitlab-pages/merge_requests/25
  - gzip --recursive --keep public/
  only:
  - master
  artifacts:
    paths:
      - public
