build-npm:
  stage: build
  image: node:8.11
  script:
  - npm install
  - npm run build:gitlab:demo
  artifacts:
    paths:
      - dist


pages:
  stage: deploy
  dependencies:
    - build-npm
  script:
  - mv public/ public_src/
  - mv dist/ public/
  - cp search_engines/google7c06555988eb9ae6.html public/google7c06555988eb9ae6.html
  # Serve a compressed version to speed up the loading
  # https://gitlab.com/gitlab-org/gitlab-pages/merge_requests/25
  - gzip --recursive --keep public/
  only:
  - master
  artifacts:
    paths:
      - public
