language: node_js
node_js:
  - "10.14"
install:
    - npm install
    - npm run build:github

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
